meta_product_name: "apprenticeship.io"
meta_title: "apprenticeship.io - for the love of non-traditional software engineers"
meta_description: "The largest community for software engineering apprenticeships in the United States"
meta_image: "apprenticeshipio-circle-cropped.png" # store in `app/assets/images/`
twitter_account: "@kamrinklauschie"
